# This script generates the mapping between MS Windows timezone names and
# tzdata/Olsen timezone names, by retrieving a file:
# http://unicode.org/cldr/data/common/supplemental/supplementalData.xml
# and parsing it, and from this generating the file windows_tz.py.
#
# It must be run with Python 3.

import re
from urllib.request import urlopen
from xml.dom import minidom
from pprint import pprint

XML_SOURCE = 'http://unicode.org/cldr/data/common/supplemental/windowsZones.xml'


def get_backward_aliases():
    backward = {}
    with open("backward.txt", encoding="ascii") as fh:
        for line in fh:
            line = line.strip()
            if not line or line[0] == "#":
                continue
            link_type, target, link_name, *_ = [item.strip() for item in re.split("\s+", line)]
            if link_type.lower() != "link":
                continue
            backward[link_name] = target
    return backward

source = urlopen(XML_SOURCE).read()
dom = minidom.parseString(source)

map_element = None
for element in dom.getElementsByTagName('mapTimezones'):
    if element.getAttribute('type') == 'windows':
        map_element = element
        break

if not map_element:
    raise ValueError("Can't find mapTimezones element")

win_tz = {}
tz_win = {}
for mapping in map_element.getElementsByTagName('mapZone'):
    if mapping.getAttribute('territory') == '001':
        win_tz[mapping.getAttribute('other')] = mapping.getAttribute('type').split(' ')[0]

    for tz_name in mapping.getAttribute('type').split(' '):
        tz_win[tz_name] = mapping.getAttribute('other')

# Etc/UTC is a common alias for Etc/GMT:
tz_win['Etc/UTC'] = 'UTC'

# Map in the backwards compatible zone names
# backwards.txt was taken from this file: tzdb-2017b.tar.lz from here:
# https://www.iana.org/time-zones
for backward_compat_name, standard_name in get_backward_aliases().items():
    win_zone = tz_win.get(standard_name, None)
    if win_zone:
        tz_win[backward_compat_name] = win_zone

with open('tzlocal/windows_tz.py', "wt") as out:
    out.write("# This file is autogenerated by the get_windows_info.py script\n"
              "# Do not edit.\nwin_tz = ")
    pprint(win_tz, out)
    out.write("\n# Old name for the win_tz variable:\ntz_names = win_tz\n\ntz_win = ")
    pprint(tz_win, out)
