name: Run the test suite

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy3.8"]
        exclude:
        - os: macos-latest
          python-version: 3.8
        - os: macos-latest
          python-version: pypy3
        - os: windows-latest
          python-version: 3.8
        - os: windows-latest
          python-version: pypy3
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-test-${{ matrix.python-version }}-${{ matrix.os }}
    - name: Install dependencies
      run: pip install .[devenv]
    - name: Test with pytest
      run: pytest
